on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download and Rename File From OBS
        uses: huaweicloud/obs-helper@v1.1.0
        id: download_file_from_obs
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: region
          bucket_name: bucket_name
          obs_file_path: src/upload/file1.txt
          local_file_path: resource/file3.txt
          operation_type: download