on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download Folder From OBS
        uses: huaweicloud/obs-helper@v1.1.0
        id: download_folder_from_obs
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: region
          bucket_name: bucket_name
          obs_file_path: src/download
          local_file_path: resource/download
          operation_type: download
          include_self_folder: yes
          exclude: |
                    src/download/obsFolder1/obsFile1-1.txt
                    src/download/obsFolder2